import { WorkoutTemplate } from '@/types'

export const DEFAULT_WORKOUTS: WorkoutTemplate[] = [
  // ── Schede personali ──────────────────────────────────────────────
  {
    id: 'gambe-spalle',
    name: 'Gambe e Spalle',
    muscleGroups: ['gambe', 'spalle', 'glutei'],
    estimatedMinutes: 85,
    description: 'Leg extension, Hack squat, Affondi + riscaldamento spalle a circuito, Alzate laterali, Trazioni',
    exercises: [
      {
        id: 'gs-leg-ext',
        name: 'Leg Extension',
        muscleGroups: ['gambe'],
        defaultSets: 3,
        defaultReps: '5+5',
        restSeconds: 90,
        tips: '5 rip gamba singola a 45kg → senza pausa 5 rip entrambe le gambe a 90kg',
        instructions: 'Siediti con la schiena ben aderente allo schienale e i polpacci sotto il rullo. Estendi entrambe le gambe fino alla posizione completamente dritta stringendo i quadricipiti in cima. Mantieni 1 secondo di pausa in estensione massima. Scendi lentamente in 3 secondi. Non sollevare i glutei dal sedile durante il movimento.',
      },
      {
        id: 'gs-hack-squat',
        name: 'Hack Squat',
        muscleGroups: ['gambe', 'glutei'],
        defaultSets: 4,
        defaultReps: '12',
        restSeconds: 120,
        tips: '60kg',
        instructions: 'Posiziona i piedi alla larghezza delle spalle con punte leggermente aperte verso l\'esterno. Schiena sempre aderente allo schienale durante tutto il movimento. Scendi lentamente finché le cosce sono parallele alla pedana o più in basso. Spingi attraverso i talloni per risalire. Non bloccare le ginocchia in cima — mantieni una leggera tensione.',
      },
      {
        id: 'gs-affondi',
        name: 'Affondi',
        muscleGroups: ['gambe', 'glutei'],
        defaultSets: 4,
        defaultReps: '12 (6/gamba)',
        restSeconds: 0,
        tips: '52kg. Dopo le prime 3 serie fai subito il blocco riscaldamento spalle (4ª serie senza blocco)',
        instructions: 'Stai in piedi con i piedi alla larghezza dei fianchi. Fai un passo lungo in avanti con una gamba. Il ginocchio anteriore si flette fino a circa 90° — non deve superare la punta del piede. Il ginocchio posteriore scende verso il pavimento senza toccarlo. Mantieni il busto eretto e il core contratto. Torna alla posizione di partenza spingendo con il tallone del piede anteriore. Alterna le gambe.',
      },
      {
        id: 'gs-risc-spalle',
        name: 'Riscaldamento Spalle (post-Affondi)',
        muscleGroups: ['spalle'],
        defaultSets: 3,
        defaultReps: '8 × 5 esercizi',
        restSeconds: 90,
        tips: '8 rip × 8kg per ciascuno senza pausa: (1) alzate lat. a metà → (2) alzate lat. complete → (3) alzate frontali a metà → (4) alzate frontali complete → (5) rematore busto inclinato gambe unite',
        instructions: 'Esegui tutti e 5 gli esercizi in sequenza senza pausa con gli stessi manubri (8kg). Mantieni i gomiti leggermente piegati in tutte le alzate. Movimento controllato e fluido — niente slancio. (1) Alzate laterali solo fino a metà ROM. (2) Alzate laterali complete fino all\'altezza delle spalle. (3) Alzate frontali a metà ROM. (4) Alzate frontali complete. (5) Busto inclinato a 45°, gambe unite, rematore con i gomiti verso l\'esterno.',
      },
      {
        id: 'gs-alzate-lat',
        name: 'Alzate Laterali',
        muscleGroups: ['spalle'],
        defaultSets: 3,
        defaultReps: '6+5',
        restSeconds: 90,
        tips: '6 rip a 16kg poi dropset immediato 5 rip a 14kg',
        instructions: 'Stai in piedi con i manubri ai lati. Inclina leggermente il busto in avanti (10–15°). Porta le braccia verso l\'esterno e in alto ruotando leggermente i polsi verso il basso (come versare un bicchiere — pollice verso il basso). Fermati quando le braccia sono all\'altezza delle spalle o appena oltre. Scendi lentamente in 3 secondi. Non usare la schiena per oscillare e non portare le braccia oltre i 90°.',
      },
      {
        id: 'gs-trazioni-larga',
        name: 'Trazioni Presa Larga',
        muscleGroups: ['schiena', 'bicipiti'],
        defaultSets: 3,
        defaultReps: '5',
        restSeconds: 120,
        instructions: 'Impugna la sbarra con presa pronata (palmi avanti) leggermente oltre la larghezza delle spalle. Inizia il movimento retraendo e abbassando le scapole — non con le braccia. Tira verso l\'alto portando il petto verso la sbarra. Scendi con controllo completo fino a quasi estensione delle braccia. Non iperestendere il collo — guarda leggermente verso l\'alto.',
      },
      {
        id: 'gs-trazioni-stretta',
        name: 'Trazioni Presa Stretta',
        muscleGroups: ['schiena', 'bicipiti'],
        defaultSets: 2,
        defaultReps: '8',
        restSeconds: 120,
        instructions: 'Presa pronate o neutra alla larghezza delle spalle o più stretta. Tira verso l\'alto portando i gomiti verso i fianchi — questo attiva maggiormente il dorsale basso. Porta il mento sopra la sbarra. Massima contrazione del dorsale in cima. Scendi in modo controllato in 2–3 secondi.',
      },
    ],
  },
  {
    id: 'petto-tricipiti',
    name: 'Petto e Tricipiti',
    muscleGroups: ['petto', 'tricipiti', 'core'],
    estimatedMinutes: 80,
    description: 'Pectoral fly, Chest press, Panca 30° manubri uniti, Tricipiti overhead + cavi, Dips, Addominali',
    exercises: [
      {
        id: 'pt-pec-fly',
        name: 'Pectoral Fly',
        muscleGroups: ['petto'],
        defaultSets: 4,
        defaultReps: '10/6/10/10',
        restSeconds: 90,
        tips: 'Schema: 27kg×10 | 32kg×6 | 37kg×10 | 37kg×10',
        instructions: 'Siediti sulla macchina e posiziona i gomiti sui cuscini — mantienili leggermente piegati per tutto il movimento. Porta le braccia verso il centro del corpo stringendo il petto in cima. Non sbattere le manopole insieme — fermati appena prima. Ritorna lentamente sentendo lo stretch nel petto. Non utilizzare la forza delle spalle per spingere.',
      },
      {
        id: 'pt-chest-press',
        name: 'Chest Press',
        muscleGroups: ['petto'],
        defaultSets: 4,
        defaultReps: '13/8/8/8 + dropset',
        restSeconds: 90,
        tips: 'Set 1: 35kg×13 | Set 2: 40kg×8 + drop 35kg×5 | Set 3-4: 45kg×8 + drop 40kg×5',
        instructions: 'Siediti con la schiena aderente allo schienale e il petto in fuori. Impugna le maniglie all\'altezza del petto con i gomiti leggermente al di sotto delle spalle. Spingi in avanti estendendo le braccia senza bloccare i gomiti in cima. Rientra lentamente — senti lo stretch nel petto. Mantieni le scapole retratte durante tutta l\'esecuzione.',
      },
      {
        id: 'pt-panca30-uniti',
        name: 'Panca 30° Manubri Uniti',
        muscleGroups: ['petto'],
        defaultSets: 3,
        defaultReps: '8 + dropset 5',
        restSeconds: 90,
        tips: '28kg × 8 rip poi dropset immediato 5 rip a 18kg. Manubri che si toccano per tutto il movimento.',
        instructions: 'Imposta la panca a 30°. Sdraiati e tieni i manubri a contatto per tutta la durata del set — questo aumenta la tensione sul petto superiore. Abbassa i manubri verso il petto lateralmente in modo controllato in 3 secondi. Spingi verso l\'alto tenendo i manubri sempre in contatto. Focus sul petto clavicolare (fascia superiore).',
      },
      {
        id: 'pt-tri-overhead',
        name: 'Estensione Tricipiti (Manubrio Verticale)',
        muscleGroups: ['tricipiti'],
        defaultSets: 3,
        defaultReps: '8',
        restSeconds: 75,
        tips: '14kg. Manubrio tenuto verticale sopra la testa, gomiti fermi.',
        instructions: 'Stai in piedi o siediti con la schiena eretta. Tieni il manubrio verticale sopra la testa con entrambe le mani avvolte attorno al piatto superiore. Gomiti puntati verso il soffitto — non si devono aprire lateralmente. Abbassa il manubrio dietro la testa flettendo solo i gomiti (non muovere le braccia superiori). Estendi completamente in cima stringendo il tricipite.',
      },
      {
        id: 'pt-tri-cavi',
        name: 'Tricipiti ai Cavi',
        muscleGroups: ['tricipiti'],
        defaultSets: 4,
        defaultReps: '10',
        restSeconds: 75,
        tips: 'Schema: 45kg×10 | 50kg×10 | 55kg×10 | 55kg×10',
        instructions: 'Stai in piedi di fronte alla macchina con i piedi alla larghezza delle spalle. Impugna la corda o la barra alta. Tieni i gomiti fissi e aderenti ai fianchi per tutto il movimento — sono il fulcro. Estendi i gomiti verso il basso fino a quando le braccia sono completamente tese. Stringi il tricipite in basso per 1 secondo. Rientra lentamente controllando il peso.',
      },
      {
        id: 'pt-dips',
        name: 'Dips',
        muscleGroups: ['tricipiti', 'petto'],
        defaultSets: 4,
        defaultReps: '8',
        restSeconds: 90,
        instructions: 'Impugna le parallele e partenza con gomiti distesi. Per focus sui tricipiti: mantieni il busto più eretto possibile con i gomiti vicini ai fianchi. Abbassati piegando i gomiti fino a circa 90°. Spingi sui palmi per risalire ed estendi completamente le braccia in cima. Per coinvolgere più petto: inclina il busto in avanti.',
      },
      {
        id: 'pt-addominali',
        name: 'Addominali + Flessioni',
        muscleGroups: ['core'],
        defaultSets: 3,
        defaultReps: '20 + 20',
        restSeconds: 60,
        tips: '20 addominali / 45 sec esercizi core, poi 20 flessioni',
        instructions: 'Crunch: sdraiato, ginocchia piegate, mani dietro la testa (senza tirare il collo). Solleva solo le spalle dal pavimento. Espira in cima e tieni 1 secondo. Core (45s): plank, mountain climbers o leg raise alternati. Flessioni: mani alla larghezza delle spalle, corpo in linea retta dalla testa ai talloni. Abbassa il petto a 5cm dal suolo.',
      },
    ],
  },
  {
    id: 'dorsali-tricipiti',
    name: 'Dorsali e Tricipiti',
    muscleGroups: ['schiena', 'tricipiti'],
    estimatedMinutes: 80,
    description: 'Pulley, Lat machine larga + stretta, Upper back, Trazioni, Dips',
    exercises: [
      {
        id: 'dt-pulley',
        name: 'Pulley (Cable Row)',
        muscleGroups: ['schiena'],
        defaultSets: 4,
        defaultReps: '8 + dropset 5',
        restSeconds: 90,
        tips: 'Set 1: 45kg×8 + drop 35kg×5 | Set 2: 50kg×8 + drop 35kg×5 | Set 3-4: 55kg×8 + drop 35kg×5',
        instructions: 'Siediti con i piedi sulla piattaforma, ginocchia leggermente piegate. Schiena eretta — non curvarti per raggiungere la manopola. Tira verso l\'ombelico portando i gomiti indietro e mantenendo le scapole retratte in cima. Espira tirando, inspira rilasciando. Ritorna lentamente alla posizione di partenza allungando le braccia senza curvare la schiena.',
      },
      {
        id: 'dt-lat-larga',
        name: 'Lat Machine Presa Larga',
        muscleGroups: ['schiena'],
        defaultSets: 3,
        defaultReps: '8 + dropset 5',
        restSeconds: 90,
        tips: 'Set 1-2: 65kg×8 + drop 45kg×5 | Set 3: 70kg×8 + drop 50kg×5',
        instructions: 'Siediti con le ginocchia bloccate sotto il pad. Presa pronata (palmi avanti) più larga delle spalle. Porta la sbarra verso il petto superiore (non dietro la testa). Inizia il movimento abbassando e retraendo le scapole — poi fletti i gomiti. Tira con i gomiti verso il basso e verso i fianchi. Risali lentamente in 3 secondi. Evita di oscillare il busto.',
      },
      {
        id: 'dt-lat-stretta',
        name: 'Lat Machine Presa Stretta (Triangolo)',
        muscleGroups: ['schiena'],
        defaultSets: 3,
        defaultReps: '8 + dropset 5',
        restSeconds: 90,
        tips: '60kg×8 poi dropset 5 rip a 45kg',
        instructions: 'Usa la manopola a triangolo (presa neutra, palmi affrontati). Con la presa stretta si attiva maggiormente il dorsale basso e il grande rotondo. Porta il triangolo verso l\'addome superiore mantenendo i gomiti vicini al busto. Scapole retratte e depresse in cima. Risali lentamente con controllo completo.',
      },
      {
        id: 'dt-upper-back',
        name: 'Upper Back',
        muscleGroups: ['schiena'],
        defaultSets: 3,
        defaultReps: '8',
        restSeconds: 90,
        tips: '40kg',
        instructions: 'Impostazione simile al rematore ma con focus sulla parte alta della schiena (trapezio medio, romboidi, infraspinato). Tieni i gomiti più alti durante il tiro — portali all\'altezza delle spalle. Spremi bene le scapole insieme in cima mantenendo 1 secondo di contrazione. Questo esercizio è fondamentale per la salute della spalla e la postura. Movimento controllato, no slancio.',
      },
      {
        id: 'dt-trazioni-larga',
        name: 'Trazioni Presa Larga',
        muscleGroups: ['schiena', 'bicipiti'],
        defaultSets: 3,
        defaultReps: '5',
        restSeconds: 120,
        instructions: 'Impugna la sbarra con presa pronata (palmi avanti) leggermente oltre la larghezza delle spalle. Inizia il movimento retraendo e abbassando le scapole — non con le braccia. Tira verso l\'alto portando il petto verso la sbarra. Scendi con controllo completo fino a quasi estensione delle braccia. Non iperestendere il collo — guarda leggermente verso l\'alto.',
      },
      {
        id: 'dt-trazioni-stretta',
        name: 'Trazioni Presa Stretta',
        muscleGroups: ['schiena', 'bicipiti'],
        defaultSets: 2,
        defaultReps: '8',
        restSeconds: 120,
        instructions: 'Presa pronate o neutra alla larghezza delle spalle o più stretta. Tira verso l\'alto portando i gomiti verso i fianchi — questo attiva maggiormente il dorsale basso. Porta il mento sopra la sbarra. Massima contrazione del dorsale in cima. Scendi in modo controllato in 2–3 secondi.',
      },
      {
        id: 'dt-dips',
        name: 'Dips',
        muscleGroups: ['tricipiti', 'petto'],
        defaultSets: 4,
        defaultReps: '8',
        restSeconds: 90,
        instructions: 'Impugna le parallele e partenza con gomiti distesi. Per focus sui tricipiti: mantieni il busto più eretto possibile con i gomiti vicini ai fianchi. Abbassati piegando i gomiti fino a circa 90°. Spingi sui palmi per risalire ed estendi completamente le braccia in cima.',
      },
    ],
  },
  {
    id: 'petto-bicipiti',
    name: 'Petto e Bicipiti',
    muscleGroups: ['petto', 'bicipiti', 'core'],
    estimatedMinutes: 75,
    description: 'Pectoral fly, Chest press, Panca angoli, Curl bilanciere + Pullover, Curl manubri panca',
    exercises: [
      {
        id: 'pb-pec-fly',
        name: 'Pectoral Fly',
        muscleGroups: ['petto'],
        defaultSets: 4,
        defaultReps: '10/6/10/10',
        restSeconds: 90,
        tips: 'Schema: 27kg×10 | 32kg×6 | 37kg×10 | 37kg×10',
      },
      {
        id: 'pb-chest-press',
        name: 'Chest Press',
        muscleGroups: ['petto'],
        defaultSets: 4,
        defaultReps: '13/8/8/8 + dropset',
        restSeconds: 90,
        tips: 'Set 1: 35kg×13 | Set 2: 40kg×8 + drop 35kg×5 | Set 3-4: 45kg×8 + drop 40kg×5',
      },
      {
        id: 'pb-panca-angoli',
        name: 'Petto Panca Multi-Angolo',
        muscleGroups: ['petto'],
        defaultSets: 2,
        defaultReps: '6×5 angoli',
        restSeconds: 120,
        tips: '14kg manubri. Per ogni serie: 6 rip a 30° → 6 a 45° → 6 a 60° → 6 a 45° → 6 a 30° (= 30 rip totali per serie)',
      },
      {
        id: 'pb-panca30-uniti',
        name: 'Panca 30° Manubri Uniti',
        muscleGroups: ['petto'],
        defaultSets: 2,
        defaultReps: '8',
        restSeconds: 90,
        tips: '26kg',
      },
      {
        id: 'pb-curl-bilanciere',
        name: 'Curl Bilanciere',
        muscleGroups: ['bicipiti'],
        defaultSets: 3,
        defaultReps: '8',
        restSeconds: 75,
        tips: '15kg bilanciere. Superset con Pullover panca piana',
      },
      {
        id: 'pb-pullover',
        name: 'Pullover Panca Piana',
        muscleGroups: ['petto', 'schiena'],
        defaultSets: 2,
        defaultReps: '8',
        restSeconds: 75,
        tips: '34kg. Eseguire subito dopo il set di curl bilanciere (superset)',
      },
      {
        id: 'pb-curl-manubri',
        name: 'Curl Manubri Panca Dritta',
        muscleGroups: ['bicipiti'],
        defaultSets: 4,
        defaultReps: '12 + dropset 5',
        restSeconds: 75,
        tips: '16kg × 12 rip poi dropset immediato 5 rip a 14kg',
      },
      {
        id: 'pb-addominali',
        name: 'Addominali + Flessioni',
        muscleGroups: ['core'],
        defaultSets: 3,
        defaultReps: '20 + 20',
        restSeconds: 60,
        tips: '20 addominali / 45 sec esercizi core, poi 20 flessioni',
      },
    ],
  },
  // ── Schede generiche ──────────────────────────────────────────────
  {
    id: 'push',
    name: 'Push — Petto / Spalle / Tricipiti',
    muscleGroups: ['petto', 'spalle', 'tricipiti'],
    estimatedMinutes: 75,
    description: 'Movimenti di spinta orizzontali e verticali',
    exercises: [
      { id: 'bench-press', name: 'Panca Piana Bilanciere', muscleGroups: ['petto'], defaultSets: 4, defaultReps: '8-10', restSeconds: 90, tips: 'Petto in fuori, scapole retratte. Abbassa lentamente 2 secondi.' },
      { id: 'incline-db', name: 'Panca Inclinata Manubri', muscleGroups: ['petto'], defaultSets: 3, defaultReps: '10-12', restSeconds: 75 },
      { id: 'cable-fly', name: 'Croci ai Cavi', muscleGroups: ['petto'], defaultSets: 3, defaultReps: '12-15', restSeconds: 60, tips: 'Mantieni gomiti leggermente piegati per tutto il movimento.' },
      { id: 'ohp', name: 'Lento Avanti Bilanciere', muscleGroups: ['spalle'], defaultSets: 4, defaultReps: '8-10', restSeconds: 90 },
      { id: 'lateral-raise', name: 'Alzate Laterali', muscleGroups: ['spalle'], defaultSets: 3, defaultReps: '12-15', restSeconds: 60, tips: 'Pollice leggermente verso il basso. Stop a 90°.' },
      { id: 'french-press', name: 'French Press', muscleGroups: ['tricipiti'], defaultSets: 3, defaultReps: '10-12', restSeconds: 75 },
      { id: 'pushdown', name: 'Push-down ai Cavi', muscleGroups: ['tricipiti'], defaultSets: 3, defaultReps: '12-15', restSeconds: 60 },
    ],
  },
  {
    id: 'pull',
    name: 'Pull — Schiena / Bicipiti',
    muscleGroups: ['schiena', 'bicipiti'],
    estimatedMinutes: 70,
    description: 'Movimenti di trazione verticali e orizzontali',
    exercises: [
      { id: 'deadlift', name: 'Stacco da Terra', muscleGroups: ['schiena', 'gambe'], defaultSets: 4, defaultReps: '5-6', restSeconds: 120, tips: 'Schiena neutra, barra vicina al corpo. Non arrotondare la lombare.' },
      { id: 'lat-pulldown', name: 'Lat Machine Presa Larga', muscleGroups: ['schiena'], defaultSets: 4, defaultReps: '8-10', restSeconds: 90, tips: 'Porta il gomito verso il fianco, non tirare con le braccia.' },
      { id: 'barbell-row', name: 'Rematore Bilanciere', muscleGroups: ['schiena'], defaultSets: 4, defaultReps: '8-10', restSeconds: 90 },
      { id: 'cable-row', name: 'Pulley Basso', muscleGroups: ['schiena'], defaultSets: 3, defaultReps: '10-12', restSeconds: 75 },
      { id: 'face-pull', name: 'Face Pull', muscleGroups: ['spalle', 'schiena'], defaultSets: 3, defaultReps: '15', restSeconds: 60, tips: 'Ottimo per la salute delle spalle. Non saltarlo mai.' },
      { id: 'barbell-curl', name: 'Curl Bilanciere', muscleGroups: ['bicipiti'], defaultSets: 4, defaultReps: '8-10', restSeconds: 75 },
      { id: 'hammer-curl', name: 'Curl Martello', muscleGroups: ['bicipiti'], defaultSets: 3, defaultReps: '10-12', restSeconds: 60 },
    ],
  },
  {
    id: 'legs',
    name: 'Legs — Gambe / Glutei',
    muscleGroups: ['gambe', 'glutei'],
    estimatedMinutes: 80,
    description: 'Lower body completo: quad, femorali, polpacci, glutei',
    exercises: [
      { id: 'squat', name: 'Squat Bilanciere', muscleGroups: ['gambe', 'glutei'], defaultSets: 4, defaultReps: '8-10', restSeconds: 120, tips: 'Profondità almeno parallela. Ginocchia in linea con le punte dei piedi.' },
      { id: 'leg-press', name: 'Leg Press', muscleGroups: ['gambe', 'glutei'], defaultSets: 4, defaultReps: '10-12', restSeconds: 90 },
      { id: 'lunges', name: 'Affondi Manubri', muscleGroups: ['gambe', 'glutei'], defaultSets: 3, defaultReps: '12/lato', restSeconds: 75 },
      { id: 'leg-curl', name: 'Leg Curl Sdraiato', muscleGroups: ['gambe'], defaultSets: 3, defaultReps: '10-12', restSeconds: 75, tips: 'Femorali: spremi in cima al movimento, scendi lentamente.' },
      { id: 'leg-ext', name: 'Leg Extension', muscleGroups: ['gambe'], defaultSets: 3, defaultReps: '12-15', restSeconds: 60 },
      { id: 'hip-thrust', name: 'Hip Thrust', muscleGroups: ['glutei'], defaultSets: 4, defaultReps: '10-12', restSeconds: 90, tips: 'Spremi il gluteo in cima per 1 secondo. Non estendere la lombare.' },
      { id: 'calf-raise', name: 'Calf Raises', muscleGroups: ['gambe'], defaultSets: 4, defaultReps: '15-20', restSeconds: 60 },
    ],
  },
  {
    id: 'upper',
    name: 'Upper Body',
    muscleGroups: ['petto', 'schiena', 'spalle', 'bicipiti', 'tricipiti'],
    estimatedMinutes: 75,
    description: 'Tutto il busto in una sessione',
    exercises: [
      { id: 'bench-press-u', name: 'Panca Piana Bilanciere', muscleGroups: ['petto'], defaultSets: 4, defaultReps: '8-10', restSeconds: 90 },
      { id: 'row-u', name: 'Rematore Bilanciere', muscleGroups: ['schiena'], defaultSets: 4, defaultReps: '8-10', restSeconds: 90 },
      { id: 'ohp-u', name: 'Lento Avanti', muscleGroups: ['spalle'], defaultSets: 3, defaultReps: '8-10', restSeconds: 90 },
      { id: 'lat-u', name: 'Lat Machine', muscleGroups: ['schiena'], defaultSets: 3, defaultReps: '10-12', restSeconds: 75 },
      { id: 'curl-u', name: 'Curl Bilanciere', muscleGroups: ['bicipiti'], defaultSets: 3, defaultReps: '10-12', restSeconds: 60 },
      { id: 'push-u', name: 'Push-down Tricipiti', muscleGroups: ['tricipiti'], defaultSets: 3, defaultReps: '10-12', restSeconds: 60 },
    ],
  },
  {
    id: 'lower',
    name: 'Lower Body',
    muscleGroups: ['gambe', 'glutei', 'core'],
    estimatedMinutes: 65,
    description: 'Gambe e core',
    exercises: [
      { id: 'squat-l', name: 'Squat Bilanciere', muscleGroups: ['gambe', 'glutei'], defaultSets: 4, defaultReps: '8-10', restSeconds: 120 },
      { id: 'rdl', name: 'Romanian Deadlift', muscleGroups: ['gambe', 'glutei'], defaultSets: 4, defaultReps: '10-12', restSeconds: 90, tips: 'Mantieni la schiena neutra, abbassa finché senti stiramento nei femorali.' },
      { id: 'leg-press-l', name: 'Leg Press', muscleGroups: ['gambe'], defaultSets: 3, defaultReps: '12-15', restSeconds: 75 },
      { id: 'hip-l', name: 'Hip Thrust', muscleGroups: ['glutei'], defaultSets: 4, defaultReps: '10-12', restSeconds: 90 },
      { id: 'plank', name: 'Plank', muscleGroups: ['core'], defaultSets: 3, defaultReps: '45 sec', restSeconds: 60 },
      { id: 'calf-l', name: 'Calf Raises', muscleGroups: ['gambe'], defaultSets: 4, defaultReps: '15-20', restSeconds: 60 },
    ],
  },
  {
    id: 'full-body',
    name: 'Full Body',
    muscleGroups: ['petto', 'schiena', 'gambe', 'spalle', 'core'],
    estimatedMinutes: 60,
    description: 'Sessione completa ideale 3 giorni/settimana',
    exercises: [
      { id: 'squat-fb', name: 'Squat Bilanciere', muscleGroups: ['gambe', 'glutei'], defaultSets: 3, defaultReps: '8-10', restSeconds: 90 },
      { id: 'bench-fb', name: 'Panca Piana', muscleGroups: ['petto'], defaultSets: 3, defaultReps: '8-10', restSeconds: 90 },
      { id: 'row-fb', name: 'Rematore Bilanciere', muscleGroups: ['schiena'], defaultSets: 3, defaultReps: '8-10', restSeconds: 90 },
      { id: 'ohp-fb', name: 'Lento Avanti', muscleGroups: ['spalle'], defaultSets: 3, defaultReps: '8-10', restSeconds: 75 },
      { id: 'rdl-fb', name: 'Romanian Deadlift', muscleGroups: ['gambe'], defaultSets: 3, defaultReps: '10-12', restSeconds: 90 },
      { id: 'plank-fb', name: 'Plank', muscleGroups: ['core'], defaultSets: 3, defaultReps: '45 sec', restSeconds: 60 },
    ],
  },
  {
    id: 'cardio',
    name: 'Cardio / HIIT',
    muscleGroups: ['cardio'],
    estimatedMinutes: 30,
    description: 'Allenamento cardiovascolare ad alta intensità',
    exercises: [
      { id: 'warmup', name: 'Riscaldamento (corsa leggera)', muscleGroups: ['cardio'], defaultSets: 1, defaultReps: '5 min', restSeconds: 0 },
      { id: 'sprint', name: 'Sprint 30s / Riposo 30s', muscleGroups: ['cardio'], defaultSets: 8, defaultReps: '30 sec', restSeconds: 30, tips: '8 round totali. Massimo sforzo negli sprint.' },
      { id: 'jump-rope', name: 'Corda (salti)', muscleGroups: ['cardio'], defaultSets: 4, defaultReps: '1 min', restSeconds: 30 },
      { id: 'burpees', name: 'Burpees', muscleGroups: ['cardio', 'core'], defaultSets: 3, defaultReps: '10', restSeconds: 45 },
      { id: 'cooldown', name: 'Defaticamento + stretching', muscleGroups: ['cardio'], defaultSets: 1, defaultReps: '5 min', restSeconds: 0 },
    ],
  },

  // ── Programmi 4 giorni/settimana ────────────────────────────────
  // Upper/Lower 4gg — Eric Helms Training Pyramid
  {
    id: 'ul4-upper-a',
    name: 'Upper/Lower 4gg — Upper A (Forza)',
    muscleGroups: ['petto', 'schiena', 'spalle', 'bicipiti', 'tricipiti'],
    estimatedMinutes: 70,
    description: 'Lunedì/Giovedì · Eric Helms Training Pyramid · Focus forza compound',
    exercises: [
      { id: 'ul-bench', name: 'Panca Piana Bilanciere', muscleGroups: ['petto'], defaultSets: 4, defaultReps: '5-6', restSeconds: 120, tips: 'Intensità alta, riposo lungo. Aumenta 2.5kg quando completi tutte le serie.' },
      { id: 'ul-row', name: 'Rematore Bilanciere', muscleGroups: ['schiena'], defaultSets: 4, defaultReps: '5-6', restSeconds: 120, tips: 'Schiena parallela, tira con i gomiti. Ugual volume della panca.' },
      { id: 'ul-ohp', name: 'Lento Avanti Bilanciere', muscleGroups: ['spalle'], defaultSets: 3, defaultReps: '6-8', restSeconds: 90 },
      { id: 'ul-latpull', name: 'Lat Machine Presa Larga', muscleGroups: ['schiena'], defaultSets: 3, defaultReps: '6-8', restSeconds: 90, tips: 'Petto alto, porta il gomito verso il fianco.' },
      { id: 'ul-curl-a', name: 'Curl Bilanciere', muscleGroups: ['bicipiti'], defaultSets: 3, defaultReps: '8-10', restSeconds: 75 },
      { id: 'ul-pushdown-a', name: 'Push-down Tricipiti ai Cavi', muscleGroups: ['tricipiti'], defaultSets: 3, defaultReps: '8-10', restSeconds: 75 },
    ],
  },
  {
    id: 'ul4-lower-a',
    name: 'Upper/Lower 4gg — Lower A (Forza)',
    muscleGroups: ['gambe', 'glutei', 'core'],
    estimatedMinutes: 75,
    description: 'Martedì/Venerdì · Eric Helms Training Pyramid · Focus forza lower',
    exercises: [
      { id: 'ul-squat', name: 'Squat Bilanciere', muscleGroups: ['gambe', 'glutei'], defaultSets: 4, defaultReps: '5-6', restSeconds: 150, tips: 'Discesa 3 secondi, risalita esplosiva. Profondità almeno parallela.' },
      { id: 'ul-rdl', name: 'Romanian Deadlift', muscleGroups: ['gambe', 'glutei'], defaultSets: 3, defaultReps: '6-8', restSeconds: 120, tips: 'Schiena neutra, senti lo stiramento nei femorali. Non arrotondare la lombare.' },
      { id: 'ul-legpress-a', name: 'Leg Press', muscleGroups: ['gambe', 'glutei'], defaultSets: 3, defaultReps: '8-10', restSeconds: 90 },
      { id: 'ul-legcurl', name: 'Leg Curl Sdraiato', muscleGroups: ['gambe'], defaultSets: 3, defaultReps: '10-12', restSeconds: 75, tips: 'Spremi il femore in cima, scendi in 3 secondi.' },
      { id: 'ul-calf-a', name: 'Calf Raises', muscleGroups: ['gambe'], defaultSets: 4, defaultReps: '12-15', restSeconds: 60 },
      { id: 'ul-plank-a', name: 'Plank / Core', muscleGroups: ['core'], defaultSets: 3, defaultReps: '45-60 sec', restSeconds: 60 },
    ],
  },
  {
    id: 'ul4-upper-b',
    name: 'Upper/Lower 4gg — Upper B (Volume)',
    muscleGroups: ['petto', 'schiena', 'spalle', 'bicipiti', 'tricipiti'],
    estimatedMinutes: 75,
    description: 'Mercoledì/Sabato · Eric Helms Training Pyramid · Volume e isolamento',
    exercises: [
      { id: 'ul-incline', name: 'Panca Inclinata Manubri', muscleGroups: ['petto'], defaultSets: 4, defaultReps: '10-12', restSeconds: 90 },
      { id: 'ul-cablerow', name: 'Pulley / Rematore al Cavo', muscleGroups: ['schiena'], defaultSets: 4, defaultReps: '10-12', restSeconds: 90, tips: 'Gomiti vicino al busto, spremi le scapole alla fine.' },
      { id: 'ul-fly', name: 'Croci ai Cavi (Cable Fly)', muscleGroups: ['petto'], defaultSets: 3, defaultReps: '12-15', restSeconds: 75, tips: 'Mantieni gomiti leggermente piegati. Senti lo stretch nel petto.' },
      { id: 'ul-facepull', name: 'Face Pull', muscleGroups: ['spalle', 'schiena'], defaultSets: 3, defaultReps: '15', restSeconds: 60, tips: 'Non saltarlo mai: fondamentale per la salute della spalla.' },
      { id: 'ul-laterale-b', name: 'Alzate Laterali', muscleGroups: ['spalle'], defaultSets: 3, defaultReps: '12-15', restSeconds: 60, tips: 'Pollice leggermente verso il basso, stop a 90°. Leggero busto in avanti.' },
      { id: 'ul-hammer', name: 'Curl Martello', muscleGroups: ['bicipiti'], defaultSets: 3, defaultReps: '10-12', restSeconds: 60 },
      { id: 'ul-dips-b', name: 'Dips (Tricipiti)', muscleGroups: ['tricipiti', 'petto'], defaultSets: 3, defaultReps: '10-12', restSeconds: 75 },
    ],
  },
  {
    id: 'ul4-lower-b',
    name: 'Upper/Lower 4gg — Lower B (Volume)',
    muscleGroups: ['gambe', 'glutei', 'core'],
    estimatedMinutes: 70,
    description: 'Giovedì/Domenica · Eric Helms Training Pyramid · Volume lower body',
    exercises: [
      { id: 'ul-legpress-b', name: 'Leg Press', muscleGroups: ['gambe', 'glutei'], defaultSets: 4, defaultReps: '12-15', restSeconds: 90 },
      { id: 'ul-hipthrust', name: 'Hip Thrust', muscleGroups: ['glutei'], defaultSets: 4, defaultReps: '12', restSeconds: 90, tips: 'Spremi il gluteo 1 secondo in cima. Non estendere la lombare.' },
      { id: 'ul-lunge-b', name: 'Affondi Alternati', muscleGroups: ['gambe', 'glutei'], defaultSets: 3, defaultReps: '12/lato', restSeconds: 75 },
      { id: 'ul-legext-b', name: 'Leg Extension', muscleGroups: ['gambe'], defaultSets: 3, defaultReps: '15', restSeconds: 60, tips: 'Pausa 1 sec in estensione massima.' },
      { id: 'ul-calf-b', name: 'Calf Raises', muscleGroups: ['gambe'], defaultSets: 4, defaultReps: '15-20', restSeconds: 60 },
      { id: 'ul-core-b', name: 'Crunch + Leg Raise', muscleGroups: ['core'], defaultSets: 3, defaultReps: '15+10', restSeconds: 60 },
    ],
  },
  // PPL+ 4gg — Amerigo Brunetti
  {
    id: 'ppl4-push',
    name: 'PPL+ 4gg — Push (Petto & Spalle & Tri)',
    muscleGroups: ['petto', 'spalle', 'tricipiti'],
    estimatedMinutes: 80,
    description: 'Lunedì · Brunetti - Programmare l\'Ipertrofia · Movimenti di spinta',
    exercises: [
      { id: 'ppl-bench', name: 'Panca Piana Bilanciere', muscleGroups: ['petto'], defaultSets: 4, defaultReps: '8-10', restSeconds: 120, tips: 'Principal movement. Aumenta 2.5kg ogni sessione se completi tutte le rip.' },
      { id: 'ppl-incline', name: 'Panca Inclinata Manubri (30°)', muscleGroups: ['petto'], defaultSets: 3, defaultReps: '10-12', restSeconds: 90 },
      { id: 'ppl-fly', name: 'Pectoral Fly', muscleGroups: ['petto'], defaultSets: 3, defaultReps: '12-15', restSeconds: 75, tips: 'Picco di contrazione, scendi in modo controllato.' },
      { id: 'ppl-ohp', name: 'Lento Avanti Bilanciere', muscleGroups: ['spalle'], defaultSets: 4, defaultReps: '8-10', restSeconds: 90 },
      { id: 'ppl-lateral', name: 'Alzate Laterali', muscleGroups: ['spalle'], defaultSets: 4, defaultReps: '12-15', restSeconds: 60, tips: 'Tecnica perfetta > peso. RIR 1-2.' },
      { id: 'ppl-pushdown', name: 'Tricipiti ai Cavi (Push-down)', muscleGroups: ['tricipiti'], defaultSets: 3, defaultReps: '10-12', restSeconds: 75 },
      { id: 'ppl-dips', name: 'Dips', muscleGroups: ['tricipiti', 'petto'], defaultSets: 3, defaultReps: '8-10', restSeconds: 90 },
    ],
  },
  {
    id: 'ppl4-pull',
    name: 'PPL+ 4gg — Pull (Schiena & Bicipiti)',
    muscleGroups: ['schiena', 'bicipiti'],
    estimatedMinutes: 75,
    description: 'Martedì · Brunetti - Programmare l\'Ipertrofia · Movimenti di trazione',
    exercises: [
      { id: 'ppl-deadlift', name: 'Stacco da Terra', muscleGroups: ['schiena', 'gambe'], defaultSets: 4, defaultReps: '5-6', restSeconds: 180, tips: 'Barra vicina alle tibie, schiena neutra, spinge il pavimento giù. Il principale pattern di forza.' },
      { id: 'ppl-latpull', name: 'Lat Machine Presa Larga', muscleGroups: ['schiena'], defaultSets: 4, defaultReps: '8-10', restSeconds: 90, tips: 'Petto alto verso la barra, gomito verso il fianco.' },
      { id: 'ppl-row', name: 'Rematore Bilanciere / Manubrio', muscleGroups: ['schiena'], defaultSets: 4, defaultReps: '10-12', restSeconds: 90 },
      { id: 'ppl-pulley', name: 'Pulley / Seated Cable Row', muscleGroups: ['schiena'], defaultSets: 3, defaultReps: '12-15', restSeconds: 75, tips: 'Spremi le scapole, mantieni il petto alto.' },
      { id: 'ppl-facepull-b', name: 'Face Pull', muscleGroups: ['spalle', 'schiena'], defaultSets: 3, defaultReps: '15', restSeconds: 60 },
      { id: 'ppl-curl', name: 'Curl Bilanciere', muscleGroups: ['bicipiti'], defaultSets: 4, defaultReps: '8-10', restSeconds: 75 },
      { id: 'ppl-hammer', name: 'Curl Martello Manubri', muscleGroups: ['bicipiti'], defaultSets: 3, defaultReps: '10-12', restSeconds: 60 },
    ],
  },
  {
    id: 'ppl4-legs',
    name: 'PPL+ 4gg — Legs (Gambe & Core)',
    muscleGroups: ['gambe', 'glutei', 'core'],
    estimatedMinutes: 75,
    description: 'Giovedì · Brunetti - Programmare l\'Ipertrofia · Lower body completo',
    exercises: [
      { id: 'ppl-squat', name: 'Squat Bilanciere', muscleGroups: ['gambe', 'glutei'], defaultSets: 4, defaultReps: '8-10', restSeconds: 150, tips: 'Pattern fondamentale. Profondità completa, ginocchia in linea con i piedi.' },
      { id: 'ppl-legpress', name: 'Leg Press', muscleGroups: ['gambe', 'glutei'], defaultSets: 3, defaultReps: '12-15', restSeconds: 90 },
      { id: 'ppl-rdl', name: 'Romanian Deadlift', muscleGroups: ['gambe', 'glutei'], defaultSets: 3, defaultReps: '10-12', restSeconds: 90 },
      { id: 'ppl-hipthrust', name: 'Hip Thrust', muscleGroups: ['glutei'], defaultSets: 3, defaultReps: '12', restSeconds: 90 },
      { id: 'ppl-legcurl', name: 'Leg Curl', muscleGroups: ['gambe'], defaultSets: 3, defaultReps: '12-15', restSeconds: 75 },
      { id: 'ppl-legext', name: 'Leg Extension', muscleGroups: ['gambe'], defaultSets: 3, defaultReps: '15', restSeconds: 60 },
      { id: 'ppl-core', name: 'Plank + Crunch + Leg Raise', muscleGroups: ['core'], defaultSets: 3, defaultReps: '1 round', restSeconds: 60, tips: '40s plank + 15 crunch + 10 leg raise = 1 round' },
    ],
  },
  {
    id: 'ppl4-upper',
    name: 'PPL+ 4gg — Upper Mix (Volume)',
    muscleGroups: ['petto', 'schiena', 'spalle', 'bicipiti', 'tricipiti'],
    estimatedMinutes: 75,
    description: 'Venerdì · Brunetti - Programmare l\'Ipertrofia · Upper body volume',
    exercises: [
      { id: 'ppl-chest2', name: 'Panca Inclinata Bilanciere', muscleGroups: ['petto'], defaultSets: 4, defaultReps: '10-12', restSeconds: 90 },
      { id: 'ppl-row2', name: 'Rematore al Cavo / Pulley', muscleGroups: ['schiena'], defaultSets: 4, defaultReps: '10-12', restSeconds: 90 },
      { id: 'ppl-fly2', name: 'Croci ai Cavi / Pec Deck', muscleGroups: ['petto'], defaultSets: 3, defaultReps: '12-15', restSeconds: 75 },
      { id: 'ppl-lat2', name: 'Lat Machine Presa Stretta', muscleGroups: ['schiena'], defaultSets: 3, defaultReps: '12', restSeconds: 75 },
      { id: 'ppl-lateral2', name: 'Alzate Laterali', muscleGroups: ['spalle'], defaultSets: 3, defaultReps: '15', restSeconds: 60 },
      { id: 'ppl-curl2', name: 'Curl Manubri Panca Inclinata', muscleGroups: ['bicipiti'], defaultSets: 3, defaultReps: '12', restSeconds: 60, tips: 'Busto inclinato a 45° → massimo allungamento del bicipite.' },
      { id: 'ppl-overhead', name: 'French Press / Overhead Tricep', muscleGroups: ['tricipiti'], defaultSets: 3, defaultReps: '12', restSeconds: 60 },
    ],
  },
]

// Placeholder per i consigli dai libri — da completare con l'input dell'utente
export const BOOK_WORKOUTS: WorkoutTemplate[] = []

// Le 4 schede personali pre-caricate come custom (Palestra schede)
export const INITIAL_CUSTOM_WORKOUTS: WorkoutTemplate[] = DEFAULT_WORKOUTS.slice(0, 4).map((t) => ({
  ...t,
  isCustom: true,
}))
